project:
  type: book
  output-dir: _book

execute:
  freeze: auto
  
book:
  title: "Forstliche Fernerkundung"
  page-footer:
   left: |
      Übungaufgaben
   right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  author: "Paul Magdon"
  description: "Übungsaufgaben für das Modul FPM08 forstliche Fernerkundung"
  repo-url: https://github.com/GISLAB-HAWK/fpm08
  search: true
  chapters:
    - index.qmd
    - uebung01.qmd
    - uebung02.qmd
    - uebung03.qmd
    - uebung04.qmd
    - uebung05.qmd
    - uebung06.qmd
    - uebung07_bildklassifikation.qmd
    - uebung08_validierung.qmd
    - uebung09_aenderungsanalyse.qmd
    - uebung10_Laserscanning.qmd
    - uebung11_Photogrammetrie.qmd
    - uebung12_Hoehenmodelle.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    lang: de
#  pdf:
#    documentclass: scrreprt
#    lang: de  # Für PDF kannst du hier auch die `lang`-Option setzen, falls notwendig

editor: source

